export const USER_LISTING_PER_PAGE = 30;
export const REPO_LISTING_PER_PAGE = 10;
export const POST_LISTING_PER_PAGE = 40;
export const COMMENTS_LISTING_PER_PAGE = 40;
export const NOTIFICATION_LISTING_PER_PAGE = 40;
export const MAX_TOKEN_LIFE_IN_SECONDS = 30;
export const MAX_USERNAME_LIFE_IN_SECONDS = 5 * 60; // 5 MINUTES
